apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: {{ .Values.name | lower | replace " " "-" }}
  namespace: {{ .Values.namespace }}
spec:
  instanceSelector:
    matchLabels:
      dashboards: {{ .Values.instanceLabel }}
  datasource:
    name: {{ .Values.name }}
    type: {{ .Values.type }}
    access: proxy
    url: {{ .Values.url }}
    {{- if .Values.isDefault }}
    isDefault: true
    {{- end }}